# Generated by Django 2.2.5 on 2019-09-09 16:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on which the object was created.', verbose_name='created at ')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on which the object was last modified.', verbose_name='modified at ')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='Profile picture')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Home address')),
                ('company', models.CharField(blank=True, help_text='Company/Organization you work or own.', max_length=30)),
                ('position', models.CharField(blank=True, help_text='Position you hold at the company/organization you work at.', max_length=50)),
                ('biography', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth Date')),
                ('first_name', models.CharField(max_length=40, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('nickname', models.CharField(blank=True, help_text="Nickname for what they're commonly known, if they have", max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('met', models.TextField(blank=True, help_text='Describe how you met the contact, likeat the park or at a party', verbose_name='How you met')),
                ('food_preferences', models.TextField(blank=True, help_text='Food preferences, quirks or allergies of the contact', verbose_name='Food preferences')),
                ('pets', models.TextField(blank=True, help_text='Pets information, as their name, breed, etc..', verbose_name='Pets')),
                ('user', models.ForeignKey(help_text='User this contact belongs', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
