# Generated by Django 2.2.5 on 2019-09-14 21:28

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='short_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True),
        ),
    ]
