# Generated by Django 2.2.5 on 2019-09-15 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations', '0004_activity_short_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='partners',
            field=models.ManyToManyField(to='relations.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='short_id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Datetime on which the object was created.', verbose_name='created at ')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Datetime on which the object was last modified.', verbose_name='modified at ')),
                ('short_id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=8, unique=True)),
                ('details', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relations.Activity')),
                ('companions', models.ManyToManyField(help_text='Contacts with who you did the activity', to='relations.Contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
