# Generated by Django 2.2.5 on 2019-09-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_auto_20190915_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='met',
            field=models.TextField(blank=True, help_text='Describe how you met the contact, likeat tahe park or at a party', verbose_name='How you met'),
        ),
    ]
