# Generated by Django 2.2.6 on 2019-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0007_auto_20190916_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='hightlights',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
