# Generated by Django 2.2.6 on 2019-10-03 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0009_auto_20191003_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
