# Generated by Django 2.2.6 on 2019-10-04 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0010_delete_mood'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-date', '-created']},
        ),
    ]
